language: node_js
node_js:
- '0.10'
deploy:
  - provider: s3
    access_key_id: AKIAIPKJ3I4AQASFCSJA
    secret_access_key:
      secure: "b6MBRNgbHDGIsHHrTYxKQQ8xSyvqzkUjFynzn3lirkYvG5wkT1BGsAQLxrZBHkFD+H6pMlIha+SXHo4+8iqDbSvVLp9n3nhKfuUBwNORjwy5/Rf/sZtzKqf+CKh6c70t7f/62cH6wtgOXZEN56c8Ip2r3WZQZ3lyMVDnf2qw9z0="
    bucket: welcome.mofostaging.net
    skip_cleanup: true
    local-dir: build
    on:
      branch: master
      repo: mozilla/webmaker-landing-pages
  - provider: s3
    access_key_id: AKIAJV6EBEENN6SY6BNQ
    secret_access_key:
      secure: "hIl3P8jKhn8VLE8h3BvW/b9Uaaz2KFlyoleK4VbivzAyd+oNSlUrLE3srAgHK//FCLvsoA1kZmAvkiHBB6JMBe/dqbfkBC+rTC16S9aG1UQtr8zmXpoQWfeJrLnC1brSQ0voTke2D+bhFgZkIuofwX5DnQi0a4JcWTlkWuupyjM="
    bucket: welcome.webmaker.org
    skip_cleanup: true
    local-dir: build
    on:
      branch: production
      repo: mozilla/webmaker-landing-pages
  - provider: heroku
    api_key:
      secure: "SWqDL0m1lhzObKiMy3yN/mDwxu4784qmr2jFPMmWIoH53AHygwyl0B9VGy43BY7FBwDXu6ho1lfx9wPyxQ2r7hcEvSmZH2p/zY07+kdJuFBsL8ccvT5ar0d/BFf6YU3PwIMOTxPGODBpEKxpEkjxHpuA1LVAcE3z0w9FEMXsV4I="
    app:
      master: webmaker-landing-pages-staging
      production: webmaker-landing-pages-prod
    on:
      repo: mozilla/webmaker-landing-pages
